image: ubuntu:14.04
  
upload_egg:
  script:
    # add git as part of the egg upload
    - apt-get update -y && apt-get install -y git
    # Check if the package is actually installable
    - apt-get install -y python curl
    - apt-get install -y python-dev libffi-dev
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    - python get-pip.py
    - pip install pyOpenSSL ndg-httpsclient pyasn1

    # make sure there's only 1 "version=" line in the business_rules/__init__.py file
    - (if [ "$(sed -n "/.*\(version\).*=.*\'.*/p" business_rules/__init__.py | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/' | wc -l)" == "1" ]; then echo "Found the version number"; else echo "Fail"; exit 33; fi);
    # update version to put custom ContextLogic version
    - version_origin=$(sed -n "/.*\(version\).*=.*\'.*/p" business_rules/__init__.py | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')
    - version_cl="$version_origin+cl$CI_PIPELINE_ID"
    - sed -i "s/$version_origin/$version_cl/g" business_rules/__init__.py
    - pip install .
    - pip show $CI_PROJECT_NAME

    # Upload to pypicloud
    - pip install twine
    - python setup.py sdist
    - twine upload --repository-url $PYPI_SERVER --username $USERNAME --password $PASSWORD dist/*
  only:
    - master
